### PR TITLE
[WIP] Change YARP_WRAP_STL_STRING default value on non-MSVC platforms

### PR DESCRIPTION
**Pull request by drdanz**
This variables makes ConstString a typedef to std::string when set to OFF.

Please note that for existing builds the value is not updated.

Please let me know what you think about this change.

### CODE REVIEW

**Comment by francesco-romano** [comment]
I agree with this change. Do you want me to test this on macOS?

**Comment by traversaro** [comment]
> Great ! But why for MVSC we need to set it to ON?

+1 

Avoiding to have C++ STL objects in the DLL interface make sense if you want to mix dll compiled with different versions of the compiler and flags of the compiler (this triggers warning C4251 https://msdn.microsoft.com/en-us/library/esew7y1w.aspx indeed) but as far as I understand we don't test/support that scenario at all, so I am not sure all the trouble is worth anything.

**Comment by francesco-romano** [comment]
```
In file included from /Users/makaveli/Projects/src/yarp/src/libYARP_OS/include/yarp/os/Network.h:16:
/Users/makaveli/Projects/src/yarp/src/libYARP_OS/include/yarp/os/QosStyle.h:15:15: error: definition of type 'ConstString' conflicts with typedef of the same name
        class ConstString;
              ^
In file included from /Users/makaveli/Projects/src/yarp/src/libYARP_OS/src/AuthHMAC.cpp:6:
In file included from /Users/makaveli/Projects/src/yarp/src/libYARP_OS/include/yarp/os/impl/AuthHMAC.h:9:
In file included from /Users/makaveli/Projects/src/yarp/src/libYARP_OS/include/yarp/os/InputStream.h:12:
/Users/makaveli/Projects/src/yarp/src/libYARP_OS/include/yarp/os/ConstString.h:20:29: note: 'ConstString' declared here
        typedef std::string ConstString;
                            ^
1 error generated.

```

**Comment by drdanz** [comment]
@francesco-romano Should be fixed by aa141f40e214cbaa954967bff597bc8dcc690ea8 and travis is happy... did you try the branch or just change the option value?

**Comment by drdanz** [comment]
> Great ! But why for MVSC we need to set it to ON?

My plan is to have it enabled for non-msvc builds in YARP 2.3.72, so that we can start testing it, then I want to change it to be just a typedef in 2.3.74, but we need to switch off C4251

Also note that this might be a breaking change in case someone used a forward declaration for "class ConstString"

**Comment by francesco-romano** [comment]
I just tried the option (given the changes in this PR)

**Comment by drdanz** [comment]
Merged.
