### ISSUE TITLE
yarpscope does not build with QCustomPlot 2

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#1963]
**Describe the bug**
yarpscope does not build with latest libqcustomplot-dev (2.0.1+dfsg1-1)

**To Reproduce**
Install debian testing, install `libqcustomplot-dev` build YARP with GUIs enabled

**Expected behavior**
Should build.

**Actual behaviour**
Build fails

**Build Log**
```
[ 82%] Building CXX object src/yarpscope/plugin/CMakeFiles/QtYARPScopePlugin.dir/plotter.cpp.o
<YARP>/src/yarpscope/plugin/plotter.cpp: In constructor ‘Plotter::Plotter(const QString&, int, int, int, int, float, float, int, const QString&, bool, QObject*)’:
<YARP>/src/yarpscope/plugin/plotter.cpp:59:53: error: ‘class QCPAxis’ has no member named ‘setTickLabelType’; did you mean ‘setTickLabelSide’?
     customPlot.axisRect()->axis(QCPAxis::atBottom)->setTickLabelType(QCPAxis::ltNumber);
                                                     ^~~~~~~~~~~~~~~~
                                                     setTickLabelSide
<YARP>/src/yarpscope/plugin/plotter.cpp:59:79: error: ‘ltNumber’ is not a member of ‘QCPAxis’
     customPlot.axisRect()->axis(QCPAxis::atBottom)->setTickLabelType(QCPAxis::ltNumber);
                                                                               ^~~~~~~~
<YARP>/src/yarpscope/plugin/plotter.cpp:60:53: error: ‘class QCPAxis’ has no member named ‘setAutoTickStep’; did you mean ‘setSubTickPen’?
     customPlot.axisRect()->axis(QCPAxis::atBottom)->setAutoTickStep(false);
                                                     ^~~~~~~~~~~~~~~
                                                     setSubTickPen
<YARP>/src/yarpscope/plugin/plotter.cpp:61:53: error: ‘class QCPAxis’ has no member named ‘setTickStep’; did you mean ‘setTicker’?
     customPlot.axisRect()->axis(QCPAxis::atBottom)->setTickStep(25);
                                                     ^~~~~~~~~~~
                                                     setTicker
<YARP>/src/yarpscope/plugin/plotter.cpp:66:16: error: ‘class QCustomPlot’ has no member named ‘addItem’; did you mean ‘hasItem’?
     customPlot.addItem(textLabel);
                ^~~~~~~
                hasItem
<YARP>/src/yarpscope/plugin/plotter.cpp: In member function ‘void Graph::appendValues(float, float)’:
<YARP>/src/yarpscope/plugin/plotter.cpp:352:27: error: ‘class QCPGraph’ has no member named ‘clearData’; did you mean ‘userData’?
         customGraphPoint->clearData();
                           ^~~~~~~~~
                           userData
<YARP>/src/yarpscope/plugin/plotter.cpp:354:22: error: ‘class QCPGraph’ has no member named ‘removeDataBefore’
         customGraph->removeDataBefore(lastX - 4*buffer_size);
                      ^~~~~~~~~~~~~~~~
<YARP>/src/yarpscope/plugin/plotter.cpp: In member function ‘void Graph::clearData()’:
<YARP>/src/yarpscope/plugin/plotter.cpp:381:22: error: ‘class QCPGraph’ has no member named ‘clearData’; did you mean ‘userData’?
         customGraph->clearData();
                      ^~~~~~~~~
                      userData
<YARP>/src/yarpscope/plugin/plotter.cpp:384:27: error: ‘class QCPGraph’ has no member named ‘clearData’; did you mean ‘userData’?
         customGraphPoint->clearData();
                           ^~~~~~~~~
                           userData
make[5]: *** [src/yarpscope/plugin/CMakeFiles/QtYARPScopePlugin.dir/build.make:113: src/yarpscope/plugin/CMakeFiles/QtYARPScopePlugin.dir/plotter.cpp.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:4904: src/yarpscope/plugin/CMakeFiles/QtYARPScopePlugin.dir/all] Error 2
make[3]: *** [Makefile:152: all] Error 2
make[2]: *** [CMakeFiles/YARP.dir/build.make:108: core/YARP/CMakeFiles/YCMStamp/YARP-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:1525: CMakeFiles/YARP.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
makeobj[0]: Leaving directory `/home/ddomenichelli/Workspace/iit_superbuild/build/robotology-superbuild'
```

**Configuration**
 - OS: linux, debian testing
 - yarp version: devel
-  compiler: gcc 8.2.0

**Comment by drdanz** [comment]
The issue is now also in Ubuntu 19.04 Disco Dingo.

I think that since at some point we will have to port it to the new version of the library, we could take the occasion to port it to [Qt Charts](https://doc.qt.io/qt-5/qtcharts-index.html)

**Comment by drdanz** [comment]
Incompatible changes from QCustomPlot 1 to QCustomPlot 2 are described there https://www.qcustomplot.com/release/2.0.0-beta/changelog.txt

**Comment by drdanz** [comment]
Relevant information from the changelog:

  - Removed QCustomPlot::addItem, not needed anymore as items now automatically register in their constructor
  - Removed QCPAxis::setAutoTicks, setAutoTickCount, setAutoTickLabels, setAutoTickStep, setAutoSubTicks, setTickLabelType, setDateTimeFormat, setDateTimeSpec,
    setTickStep, setTickVector, setTickVectorLabels, setSubTickCount in favor of new QCPAxisTicker-based interface

I could not find any info about `QCPGraph::clearData` and `QCPGraph::removeDataBefore`

**Comment by drdanz** [comment]
BTW, the workaroud to build it on debian testing and ubuntu disco, if the libqcustomplot-dev package is installed is to set `YARP_USE_SYSTEM_QCustomPlot` to `OFF`

**Comment by drdanz** [comment]
Fixed in #2012
