### PR TITLE
New class for return values of interface methods PART2

### PR DESCRIPTION
**Pull request by randaz81**
sequel of https://github.com/robotology/yarp/pull/3051.
All navigation interfaces/devices have been updated to use yarp::dev::ReturnValue

### CODE REVIEW

**Comment by PeterBowman** [comment]
Hello, @randaz81. After the merge, I am getting build errors on Ubuntu 22.04 + Clang 14.0.0 ([CI logs](https://github.com/user-attachments/files/18586053/10_Build.YARP.txt)):

```
[ 33%] Building CXX object src/libYARP_dev/src/CMakeFiles/YARP_dev.dir/yarp/dev/ISpeechSynthesizer.cpp.o
In file included from /home/runner/work/tools/tools/.deps/yarp/src/libYARP_dev/src/yarp/dev/ISpeechSynthesizer.cpp:6:
In file included from /home/runner/work/tools/tools/.deps/yarp/src/libYARP_dev/src/yarp/dev/ISpeechSynthesizer.h:11:
/home/runner/work/tools/tools/.deps/yarp/src/libYARP_dev/src/yarp/dev/ReturnValue.h:76:63: error: no type named 'source_location' in namespace 'std'
inline ReturnValue YARP_METHOD_NOT_YET_IMPLEMENTED(const std::source_location& location = std::source_location::current())
                                                         ~~~~~^
/home/runner/work/tools/tools/.deps/yarp/src/libYARP_dev/src/yarp/dev/ReturnValue.h:76:96: error: no member named 'source_location' in namespace 'std'
inline ReturnValue YARP_METHOD_NOT_YET_IMPLEMENTED(const std::source_location& location = std::source_location::current())
                                                                                          ~~~~~^
/home/runner/work/tools/tools/.deps/yarp/src/libYARP_dev/src/yarp/dev/ReturnValue.h:81:54: error: no type named 'source_location' in namespace 'std'
inline ReturnValue YARP_METHOD_DEPRECATED(const std::source_location& location = std::source_location::current())
                                                ~~~~~^
/home/runner/work/tools/tools/.deps/yarp/src/libYARP_dev/src/yarp/dev/ReturnValue.h:81:87: error: no member named 'source_location' in namespace 'std'
inline ReturnValue YARP_METHOD_DEPRECATED(const std::source_location& location = std::source_location::current())
                                                                                 ~~~~~^
4 errors generated.
gmake[2]: *** [src/libYARP_dev/src/CMakeFiles/YARP_dev.dir/build.make:577: src/libYARP_dev/src/CMakeFiles/YARP_dev.dir/yarp/dev/ISpeechSynthesizer.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:4888: src/libYARP_dev/src/CMakeFiles/YARP_dev.dir/all] Error 2
gmake: *** [Makefile:171: all] Error 2
Error: Process completed with exit code 2.
```

Basically: `no type named 'source_location' in namespace 'std'`. According to [cppreference](https://en.cppreference.com/w/cpp/utility/source_location), this is a C++20 feature.

**Comment by randaz81** [comment]
Here is the issue: clang 14 is supposed to support c++20 (in fact this is checked by yarp code), but not all its features. 
While we consider if this is an issue to manage (or update minimum requirements) I recommend to switch to clang 17, which is successfully tested on ubuntu 22.04 by yarp CI.

**Comment by randaz81** [comment]
> By the way, @randaz81, shouldn't `target_compiler_features()` be updated as well to point at `cxx_std_20`? See [search results](https://github.com/search?q=repo%3Arobotology%2Fyarp+target_compile_features&type=code&p=1). Currently, C++20 is required to compile YARP, but dependent projects only need C++17 due to this.

Thank you! That piece of the code was indeed forgotten and not updated!
