### ISSUE TITLE
Build error related to missing `libsqlite3-dev` 

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp#2859]
**Describe the bug**

Hi @randaz81, @traversaro 

While compiling `yarp@master` in a docker image yesterday (15 Jun 2022), I got the following error:
```
In file included from /yarp/src/libYARP_serversql/src/yarp/serversql/impl/TripleSourceCreator.cpp:10:
/yarp/src/libYARP_serversql/src/yarp/serversql/impl/SqliteTripleSource.h:13:10: fatal error: sqlite3.h: No such file or directory
13 | #include <sqlite3.h>
| ^~~~~~~~~~~
```

I fixed it via [installing `libsqlite3-dev`](https://github.com/pattacini/dockerfiles/compare/94f4ecbb4253aabbcbff4dd6bbb61be340052d98...master), which apparently wasn't explicitly required before.

**To Reproduce**
- Here's the [dockerfile](https://github.com/pattacini/dockerfiles/blob/master/technical-evaluation-stack/gitpod/Dockerfile).
- Here are the latest [dockerhub logs](https://hub.docker.com/repository/docker/pattacini/technical-evaluation-stack/builds).

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - OS:
 - yarp version:
-  compiler:

**Additional context**

**Comment by randaz81** [comment]
Maybe introduced by https://github.com/robotology/yarp/pull/2852 ? 
@traversaro can you check it?
