### ISSUE TITLE
Regression in external projects linking libYARP_dev on yarp-3.3 branch

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp#2217]
**Describe the bug**
Since https://github.com/robotology/yarp/pull/2216 has  been merged, some downstream project that link `libYARP_dev` are not able to link correctly anymore.

**To Reproduce**
Compile icub-main master branch, it will fail during linking.

**Expected behavior**
The compilation should be successful.

**Screenshots**
Example of failed icub-main build with latest yarp-3.3 :  
~~~
[ 44%] Linking CXX executable ../../../bin/controlBoardDumper
cd /home/straversaro/src/robotology-superbuild/build/robotology/ICUB/src/tools/controlBoardDumper && /usr/bin/cmake -E cmake_link_script CMakeFiles/controlBoardDumper.dir/link.txt --verbose=1
/usr/lib/ccache/c++  -O3 -DNDEBUG   CMakeFiles/controlBoardDumper.dir/dumperThread.cpp.o CMakeFiles/controlBoardDumper.dir/genericControlBoardDumper.cpp.o CMakeFiles/controlBoardDumper.dir/main.cpp.o  -o ../../../bin/controlBoardDumper  -Wl,-rpath,/home/straversaro/src/robotology-superbuild/build/install/lib:::::::::::::::::::::::::::::::::::: /home/straversaro/src/robotology-superbuild/build/install/lib/libYARP_init.so.3.3.2 /home/straversaro/src/robotology-superbuild/build/install/lib/libYARP_math.so.3.3.2 /home/straversaro/src/robotology-superbuild/build/install/lib/libYARP_sig.so.3.3.2 /home/straversaro/src/robotology-superbuild/build/install/lib/libYARP_os.so.3.3.2 
CMakeFiles/controlBoardDumper.dir/main.cpp.o: In function `bool yarp::dev::DeviceDriver::view<yarp::dev::IPreciselyTimed>(yarp::dev::IPreciselyTimed*&)':
main.cpp:(.text._ZN4yarp3dev12DeviceDriver4viewINS0_15IPreciselyTimedEEEbRPT_[_ZN4yarp3dev12DeviceDriver4viewINS0_15IPreciselyTimedEEEbRPT_]+0x20): undefined reference to `typeinfo for yarp::dev::IPreciselyTimed'
CMakeFiles/controlBoardDumper.dir/main.cpp.o: In function `DumpModule::DumpModule()':
main.cpp:(.text._ZN10DumpModuleC2Ev[_ZN10DumpModuleC5Ev]+0xc6): undefined reference to `yarp::dev::PolyDriver::PolyDriver()'
main.cpp:(.text._ZN10DumpModuleC2Ev[_ZN10DumpModuleC5Ev]+0xd5): undefined reference to `yarp::dev::PolyDriver::PolyDriver()'
main.cpp:(.text._ZN10DumpModuleC2Ev[_ZN10DumpModuleC5Ev]+0x31d): undefined reference to `yarp::dev::PolyDriver::~PolyDriver()'
main.cpp:(.text._ZN10DumpModuleC2Ev[_ZN10DumpModuleC5Ev]+0x32d): undefined reference to `yarp::dev::PolyDriver::~PolyDriver()'
CMakeFiles/controlBoardDumper.dir/main.cpp.o: In function `DumpModule::~DumpModule()':
main.cpp:(.text._ZN10DumpModuleD2Ev[_ZN10DumpModuleD5Ev]+0x1a): undefined reference to `yarp::dev::PolyDriver::~PolyDriver()'
main.cpp:(.text._ZN10DumpModuleD2Ev[_ZN10DumpModuleD5Ev]+0x26): undefined reference to `yarp::dev::PolyDriver::~PolyDriver()'
CMakeFiles/controlBoardDumper.dir/main.cpp.o: In function `DumpModule::~DumpModule()':
main.cpp:(.text._ZN10DumpModuleD0Ev[_ZN10DumpModuleD5Ev]+0x1a): undefined reference to `yarp::dev::PolyDriver::~PolyDriver()'
CMakeFiles/controlBoardDumper.dir/main.cpp.o:main.cpp:(.text._ZN10DumpModuleD0Ev[_ZN10DumpModuleD5Ev]+0x26): more undefined references to `yarp::dev::PolyDriver::~PolyDriver()' follow
CMakeFiles/controlBoardDumper.dir/main.cpp.o: In function `DumpModule::close()':
main.cpp:(.text._ZN10DumpModule5closeEv[_ZN10DumpModule5closeEv]+0x159): undefined reference to `yarp::dev::PolyDriver::isValid() const'
main.cpp:(.text._ZN10DumpModule5closeEv[_ZN10DumpModule5closeEv]+0x1d8): undefined reference to `yarp::dev::PolyDriver::isValid() const'
main.cpp:(.text._ZN10DumpModule5closeEv[_ZN10DumpModule5closeEv]+0x2bc): undefined reference to `yarp::dev::PolyDriver::close()'
main.cpp:(.text._ZN10DumpModule5closeEv[_ZN10DumpModule5closeEv]+0x2cc): undefined reference to `yarp::dev::PolyDriver::close()'
CMakeFiles/controlBoardDumper.dir/main.cpp.o: In function `DumpModule::configure(yarp::os::ResourceFinder&)':
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x1732): undefined reference to `yarp::dev::PolyDriver::open(yarp::os::Searchable&)'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x173a): undefined reference to `yarp::dev::PolyDriver::isValid() const'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x176b): undefined reference to `yarp::dev::PolyDriver::open(yarp::os::Searchable&)'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x1773): undefined reference to `yarp::dev::PolyDriver::isValid() const'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x1a43): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x1c3f): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x1c4f): undefined reference to `typeinfo for yarp::dev::IPreciselyTimed'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x1d4b): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x1f42): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x1f52): undefined reference to `typeinfo for yarp::dev::IPreciselyTimed'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x2381): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x257c): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x258c): undefined reference to `typeinfo for yarp::dev::IPreciselyTimed'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x2641): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x283d): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x284d): undefined reference to `typeinfo for yarp::dev::IPreciselyTimed'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x29ea): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x3219): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x3708): undefined reference to `yarp::dev::Drivers::factory()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x38e3): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x43e6): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
main.cpp:(.text._ZN10DumpModule9configureERN4yarp2os14ResourceFinderE[_ZN10DumpModule9configureERN4yarp2os14ResourceFinderE]+0x5329): undefined reference to `yarp::dev::PolyDriver::getImplementation()'
collect2: error: ld returned 1 exit status
src/tools/controlBoardDumper/CMakeFiles/controlBoardDumper.dir/build.make:117: recipe for target 'bin/controlBoardDumper' failed
make[2]: *** [bin/controlBoardDumper] Error 1
make[2]: Leaving directory '/home/straversaro/src/robotology-superbuild/build/robotology/ICUB'
CMakeFiles/Makefile2:3749: recipe for target 'src/tools/controlBoardDumper/CMakeFiles/controlBoardDumper.dir/all' failed
make[1]: *** [src/tools/controlBoardDumper/CMakeFiles/controlBoardDumper.dir/all] Error 2
make[1]: Leaving directory '/home/straversaro/src/robotology-superbuild/build/robotology/ICUB'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
~~~

**Configuration (please complete the following information):**
 - OS: Ubuntu 18.04
 - yarp version: https://github.com/robotology/yarp/commit/8c462bfc7d961ccb929452039272f8f12b1372ed
-  compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Additional context**
robotology-superbuild failed build: https://github.com/robotology/robotology-superbuild/runs/476181610?check_suite_focus=true

**Comment by traversaro** [comment]
The problem is this warning when `find_package(YARP)` is invoked: 
~~~
-- Found YCM: /home/straversaro/src/robotology-superbuild/build/install/lib/cmake/YCM (found version "0.11.0.1-20191204+gitad8bb25")
CMake Warning at /home/straversaro/src/robotology-superbuild/build/install/lib/cmake/YARP/YARPConfig.cmake:194 (find_package):
  Found package configuration file:

    /home/straversaro/src/robotology-superbuild/build/install/lib/cmake/YARP_dev/YARP_devConfig.cmake

  but it set YARP_dev_FOUND to FALSE so package "YARP_dev" is considered to
  be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  YARP::YARP_math

Call Stack (most recent call first):
  CMakeLists.txt:16 (find_package)
~~~

**Comment by traversaro** [comment]
Fix for the issue provided in https://github.com/robotology/yarp/pull/2218 .

**Comment by traversaro** [comment]
Unfortunatly the issue is still present in `yarp-3.3`, as I opened PR https://github.com/robotology/yarp/pull/2218 against the wrong branch, see https://github.com/robotology/yarp/pull/2218#issuecomment-592948494 .

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/yarp/pull/2218 and https://github.com/robotology/yarp/commit/a90e44fcbaffe3b5ff5657d4aeac9d691d5e6aba ,
