### PR TITLE
Fix compilation error as std::nan is used without cmath

### PR DESCRIPTION
**Pull request by traversaro**
Fix regression in https://github.com/robotology/yarp/pull/2854 . `std::isnan` is used, but `math.h` is included, instead of `cmath` that actually defines `std::isnan`.

### CODE REVIEW

**Comment by traversaro** [comment]
> Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update the release notes by adding a file in `doc/release/<target_branch>`, based on your changes.

This is a fix of an issue that was introduced in https://github.com/robotology/yarp/pull/2854 and was not part of any release, so I do not think that adding anything in a release note would be helpful.

**Review by randaz81 — APPROVED** [review]
